from __future__ import annotations

from typing import Any, Sequence

__version__: str


class PruningStats:
    @property
    def candidates_considered(self) -> int: ...
    @property
    def candidates_pruned(self) -> int: ...


class SegmentStats:
    @property
    def start(self) -> int: ...
    @property
    def end(self) -> int: ...
    @property
    def mean(self) -> list[float] | None: ...
    @property
    def variance(self) -> list[float] | None: ...
    @property
    def count(self) -> int: ...
    @property
    def missing_count(self) -> int: ...


class Diagnostics:
    @property
    def n(self) -> int: ...
    @property
    def d(self) -> int: ...
    @property
    def schema_version(self) -> int: ...
    @property
    def engine_version(self) -> str | None: ...
    @property
    def runtime_ms(self) -> int | None: ...
    @property
    def notes(self) -> list[str]: ...
    @property
    def warnings(self) -> list[str]: ...
    @property
    def algorithm(self) -> str: ...
    @property
    def cost_model(self) -> str: ...
    @property
    def seed(self) -> int | None: ...
    @property
    def repro_mode(self) -> str: ...
    @property
    def thread_count(self) -> int | None: ...
    @property
    def blas_backend(self) -> str | None: ...
    @property
    def cpu_features(self) -> list[str] | None: ...
    @property
    def params_json(self) -> Any | None: ...
    @property
    def pruning_stats(self) -> PruningStats | None: ...
    @property
    def missing_policy_applied(self) -> str | None: ...
    @property
    def missing_fraction(self) -> float | None: ...
    @property
    def effective_sample_count(self) -> int | None: ...


class OfflineChangePointResult:
    @property
    def breakpoints(self) -> list[int]: ...
    @property
    def change_points(self) -> list[int]: ...
    @property
    def scores(self) -> list[float] | None: ...
    @property
    def segments(self) -> list[SegmentStats] | None: ...
    @property
    def diagnostics(self) -> Diagnostics: ...
    def to_json(self) -> str: ...


class Pelt:
    def __init__(
        self,
        model: str = "l2",
        min_segment_len: int = 2,
        jump: int = 1,
        max_change_points: int | None = None,
    ) -> None: ...
    def fit(self, values: Any) -> Pelt: ...
    def predict(
        self, *, pen: float | None = None, n_bkps: int | None = None
    ) -> OfflineChangePointResult: ...


class SmokeDetector:
    def __init__(self) -> None: ...
    def fit(self, values: Sequence[float]) -> SmokeDetector: ...
    def predict(self) -> list[int]: ...


def smoke_detect(values: Sequence[float]) -> list[int]: ...
