from typing import Sequence

__version__: str

class SmokeDetector:
    def __init__(self) -> None: ...
    def fit(self, values: Sequence[float]) -> SmokeDetector: ...
    def predict(self) -> list[int]: ...

def smoke_detect(values: Sequence[float]) -> list[int]: ...
